const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');
const util = require('util');
const logger = require('../utils/logger');
const { uploadDir } = require('../utils/upload');

const execFileAsync = util.promisify(execFile);

/**
 * Convert Word (DOCX) to PDF exactly.
 * Uses native Microsoft COM automation via PowerShell for 100% accurate format preservation.
 */
exports.wordToPdf = async (req, res, next) => {
  const file = req.file;
  if (!file) {
    return res.status(400).json({ success: false, error: 'Please upload a Word document' });
  }

  try {
    // Determine Paths
    const inputPath = path.resolve(file.path);
    const outputPath = path.resolve(path.join(uploadDir, `converted-${Date.now()}.pdf`));
    const scriptPath = path.resolve(path.join(__dirname, '..', 'utils', 'word2pdf.ps1'));

    logger.info(`Starting native MS Word COM conversion script for ${inputPath}`);

    // Execute PowerShell
    const { stdout, stderr } = await execFileAsync('powershell', [
      '-ExecutionPolicy', 'Bypass',
      '-NoProfile',
      '-File', scriptPath,
      inputPath,
      outputPath
    ]);

    if (stderr && stderr.trim().length > 0) {
      throw new Error(`COM Error: ${stderr.trim()}`);
    }

    if (!fs.existsSync(outputPath)) {
        throw new Error('PDF file was not generated by Word Application');
    }

    logger.info('Converted DOCX to PDF perfectly via MS COM Runtime');

    res.download(outputPath, 'converted.pdf', () => {
      fs.unlink(inputPath, () => {});
      fs.unlink(outputPath, () => {});
    });
  } catch (err) {
    fs.unlink(file.path, () => {});
    logger.error('Word COM Conversion Error: ' + err.message);
    next(err);
  }
};
