const fs = require('fs');
const path = require('path');
const { execFile } = require('child_process');
const util = require('util');
const mammoth = require('mammoth');
const puppeteer = require('puppeteer');
const logger = require('../utils/logger');
const { uploadDir } = require('../utils/upload');
const { withFallback } = require('../utils/fallback');

const execFileAsync = util.promisify(execFile);

/**
 * Best-fidelity path: native Microsoft Word COM automation via PowerShell.
 * Only works on Windows with a licensed, installed copy of MS Word - which is
 * never true inside the project's own Docker image (node:18-alpine has
 * neither PowerShell nor Word), so this must never be the *only* path.
 */
async function convertViaWordCom(inputPath, outputPath) {
  if (process.platform !== 'win32') {
    throw new Error('MS Word COM automation is only available on Windows (current platform: ' + process.platform + ')');
  }

  const scriptPath = path.resolve(path.join(__dirname, '..', 'utils', 'word2pdf.ps1'));

  const { stderr } = await execFileAsync('powershell', [
    '-ExecutionPolicy', 'Bypass',
    '-NoProfile',
    '-File', scriptPath,
    inputPath,
    outputPath,
  ]);

  if (stderr && stderr.trim().length > 0) {
    throw new Error(`COM Error: ${stderr.trim()}`);
  }
  if (!fs.existsSync(outputPath)) {
    throw new Error('PDF file was not generated by Word Application');
  }
}

/**
 * Cross-platform path: mammoth converts the DOCX's content to HTML, then a
 * headless Chromium (already a dependency for pdf-to-jpg) prints that HTML to
 * PDF. This won't reproduce every Word layout feature pixel-for-pixel, but it
 * works anywhere Node + Chromium run - including Linux containers - which
 * COM automation cannot do at all.
 */
async function convertViaMammothAndPuppeteer(inputPath, outputPath) {
  const { value: bodyHtml, messages } = await mammoth.convertToHtml({ path: inputPath });

  if (messages && messages.length > 0) {
    const warnings = messages.filter((m) => m.type === 'warning').map((m) => m.message);
    if (warnings.length > 0) {
      logger.warn(`mammoth conversion warnings: ${warnings.join('; ')}`);
    }
  }

  const fullHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: Calibri, Arial, sans-serif; font-size: 12pt; line-height: 1.5; color: #111; }
  img { max-width: 100%; }
  table { border-collapse: collapse; width: 100%; }
  td, th { border: 1px solid #ccc; padding: 4px 8px; }
</style>
</head>
<body>${bodyHtml}</body>
</html>`;

  let browser;
  try {
    browser = await puppeteer.launch({
      headless: 'new',
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    const page = await browser.newPage();
    await page.setContent(fullHtml, { waitUntil: 'networkidle0' });
    await page.pdf({
      path: outputPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '1in', bottom: '1in', left: '1in', right: '1in' },
    });
  } finally {
    if (browser) {
      await browser.close();
    }
  }

  if (!fs.existsSync(outputPath)) {
    throw new Error('PDF file was not generated by the mammoth/Puppeteer fallback');
  }
}

/**
 * Convert Word (DOCX) to PDF.
 * Tries native MS Word COM automation first (best fidelity, Windows-only),
 * then falls back to a cross-platform mammoth + Puppeteer conversion that
 * works in the project's own Docker/Linux deployment.
 */
exports.wordToPdf = async (req, res, next) => {
  const file = req.file;
  if (!file) {
    return res.status(400).json({ success: false, error: 'Please upload a Word document' });
  }

  const inputPath = path.resolve(file.path);
  const outputPath = path.resolve(path.join(uploadDir, `converted-${Date.now()}.pdf`));

  try {
    await withFallback(
      () => convertViaWordCom(inputPath, outputPath),
      () => convertViaMammothAndPuppeteer(inputPath, outputPath),
      'word-to-pdf'
    );

    logger.info(`Converted DOCX to PDF: ${outputPath}`);

    res.download(outputPath, 'converted.pdf', (err) => {
      if (err) logger.error(`Word-to-PDF download error: ${err.message}`);
      fs.unlink(inputPath, () => {});
      fs.unlink(outputPath, () => {});
    });
  } catch (err) {
    fs.unlink(file.path, () => {});
    logger.error('Word to PDF conversion error: ' + err.message);
    next(err);
  }
};
